<?php 
    return [
        [
            'user_id' => 1,
            'title' => 'Tournista',
            'hourly_rate' => 100,00,
            'description' => 'Stai per andare a fare un live e ti manca un componente? Ecco il tipo di performance che fa per te!',
        ],
        [
            'user_id' => 2,
            'title' => 'Insegnante',
            'hourly_rate' => 25,00,
            'description' => 'Se stai imparando uno strumento e vuoi intraprendere un percorso di apprendimento, questo è il tipo di performance che fa al caso tuo!',
        ],
        [
            'user_id' => 3,
            'title' => 'Tecnico del suono',
            'hourly_rate' => 150,00,
            'description' => 'Se ti serve un professionista per rendere il tuo live indimenticabile, rivolgiti ad un Tecnico del suono!',
        ],
        [
            'user_id' => 4,
            'title' => 'Band',
            'hourly_rate' => 10,00,
            'description' => 'Se nella tua band hai un posto libero, perché non chiedere aiuto ad un professionista? Potreste fare amicizia e vivere insieme esperienze incredibili!',
        ],
        [
            'user_id' => 5,
            'title' => 'Autore',
            'hourly_rate' => 50,00,
            'description' => "Non trovi l'ispirazione giusta per i tuoi testi ma la tua musica spacca? Rivolgiti ad uno dei nostri bardi, che provvederà ad aiutrti con le tue liriche!",
        ],
        [
            'user_id' => 6,
            'title' => 'Compositore',
            'hourly_rate' => 50,00,
            'description' => "Se vuoi trovare arranggiamenti per le tue composizioni per ottenere musiche sensazionali, contattami! Sono il Bardo che fa al caso tuo!",
        ],
        [
            'user_id' => 7,
            'title' => 'Tournista',
            'hourly_rate' => 100,00,
            'description' => 'Stai per andare a fare un live e ti manca un componente? Ecco il tipo di performance che fa per te!',
        ],
        [
            'user_id' => 8,
            'title' => 'Insegnante',
            'hourly_rate' => 25,00,
            'description' => 'Se stai imparando uno strumento e vuoi intraprendere un percorso di apprendimento, questo è il tipo di performance che fa al caso tuo!',
        ],
        [
            'user_id' => 9,
            'title' => 'Tecnico del suono',
            'hourly_rate' => 150,00,
            'description' => 'Se ti serve un professionista per rendere il tuo live indimenticabile, rivolgiti ad un Tecnico del suono!',
        ],
        [
            'user_id' => 10,
            'title' => 'Band',
            'hourly_rate' => 10,00,
            'description' => 'Se nella tua band hai un posto libero, perché non chiedere aiuto ad un professionista? Potreste fare amicizia e vivere insieme esperienze incredibili!',
        ],
        [
            'user_id' => 11,
            'title' => 'Autore',
            'hourly_rate' => 50,00,
            'description' => "Non trovi l'ispirazione giusta per i tuoi testi ma la tua musica spacca? Rivolgiti ad uno dei nostri bardi, che provvederà ad aiutrti con le tue liriche!",
        ],
        [
            'user_id' => 12,
            'title' => 'Compositore',
            'hourly_rate' => 50,00,
            'description' => "Se vuoi trovare arranggiamenti per le tue composizioni per ottenere musiche sensazionali, contattami! Sono il Bardo che fa al caso tuo!",
        ],        [
            'user_id' => 13,
            'title' => 'Tournista',
            'hourly_rate' => 100,00,
            'description' => 'Stai per andare a fare un live e ti manca un componente? Ecco il tipo di performance che fa per te!',
        ],
        [
            'user_id' => 14,
            'title' => 'Insegnante',
            'hourly_rate' => 25,00,
            'description' => 'Se stai imparando uno strumento e vuoi intraprendere un percorso di apprendimento, questo è il tipo di performance che fa al caso tuo!',
        ],
        [
            'user_id' => 15,
            'title' => 'Tecnico del suono',
            'hourly_rate' => 150,00,
            'description' => 'Se ti serve un professionista per rendere il tuo live indimenticabile, rivolgiti ad un Tecnico del suono!',
        ],
        [
            'user_id' => 16,
            'title' => 'Band',
            'hourly_rate' => 10,00,
            'description' => 'Se nella tua band hai un posto libero, perché non chiedere aiuto ad un professionista? Potreste fare amicizia e vivere insieme esperienze incredibili!',
        ],
        [
            'user_id' => 17,
            'title' => 'Autore',
            'hourly_rate' => 50,00,
            'description' => "Non trovi l'ispirazione giusta per i tuoi testi ma la tua musica spacca? Rivolgiti ad uno dei nostri bardi, che provvederà ad aiutrti con le tue liriche!",
        ],
        [
            'user_id' => 18,
            'title' => 'Compositore',
            'hourly_rate' => 50,00,
            'description' => "Se vuoi trovare arranggiamenti per le tue composizioni per ottenere musiche sensazionali, contattami! Sono il Bardo che fa al caso tuo!",
        ],        [
            'user_id' => 19,
            'title' => 'Tournista',
            'hourly_rate' => 100,00,
            'description' => 'Stai per andare a fare un live e ti manca un componente? Ecco il tipo di performance che fa per te!',
        ],
        [
            'user_id' => 20,
            'title' => 'Insegnante',
            'hourly_rate' => 25,00,
            'description' => 'Se stai imparando uno strumento e vuoi intraprendere un percorso di apprendimento, questo è il tipo di performance che fa al caso tuo!',
        ],
        [
            'user_id' => 21,
            'title' => 'Tecnico del suono',
            'hourly_rate' => 150,00,
            'description' => 'Se ti serve un professionista per rendere il tuo live indimenticabile, rivolgiti ad un Tecnico del suono!',
        ],
        [
            'user_id' => 22,
            'title' => 'Band',
            'hourly_rate' => 10,00,
            'description' => 'Se nella tua band hai un posto libero, perché non chiedere aiuto ad un professionista? Potreste fare amicizia e vivere insieme esperienze incredibili!',
        ],
        [
            'user_id' => 23,
            'title' => 'Autore',
            'hourly_rate' => 50,00,
            'description' => "Non trovi l'ispirazione giusta per i tuoi testi ma la tua musica spacca? Rivolgiti ad uno dei nostri bardi, che provvederà ad aiutrti con le tue liriche!",
        ],
        [
            'user_id' => 24,
            'title' => 'Compositore',
            'hourly_rate' => 50,00,
            'description' => "Se vuoi trovare arranggiamenti per le tue composizioni per ottenere musiche sensazionali, contattami! Sono il Bardo che fa al caso tuo!",
        ],        [
            'user_id' => 25,
            'title' => 'Tournista',
            'hourly_rate' => 100,00,
            'description' => 'Stai per andare a fare un live e ti manca un componente? Ecco il tipo di performance che fa per te!',
        ],
        [
            'user_id' => 26,
            'title' => 'Insegnante',
            'hourly_rate' => 25,00,
            'description' => 'Se stai imparando uno strumento e vuoi intraprendere un percorso di apprendimento, questo è il tipo di performance che fa al caso tuo!',
        ],
        [
            'user_id' => 27,
            'title' => 'Tecnico del suono',
            'hourly_rate' => 150,00,
            'description' => 'Se ti serve un professionista per rendere il tuo live indimenticabile, rivolgiti ad un Tecnico del suono!',
        ],
        [
            'user_id' => 28,
            'title' => 'Band',
            'hourly_rate' => 10,00,
            'description' => 'Se nella tua band hai un posto libero, perché non chiedere aiuto ad un professionista? Potreste fare amicizia e vivere insieme esperienze incredibili!',
        ],
        [
            'user_id' => 29,
            'title' => 'Autore',
            'hourly_rate' => 50,00,
            'description' => "Non trovi l'ispirazione giusta per i tuoi testi ma la tua musica spacca? Rivolgiti ad uno dei nostri bardi, che provvederà ad aiutrti con le tue liriche!",
        ],
        [
            'user_id' => 30,
            'title' => 'Compositore',
            'hourly_rate' => 50,00,
            'description' => "Se vuoi trovare arranggiamenti per le tue composizioni per ottenere musiche sensazionali, contattami! Sono il Bardo che fa al caso tuo!",
        ],        [
            'user_id' => 31,
            'title' => 'Tournista',
            'hourly_rate' => 100,00,
            'description' => 'Stai per andare a fare un live e ti manca un componente? Ecco il tipo di performance che fa per te!',
        ],
        [
            'user_id' => 32,
            'title' => 'Insegnante',
            'hourly_rate' => 25,00,
            'description' => 'Se stai imparando uno strumento e vuoi intraprendere un percorso di apprendimento, questo è il tipo di performance che fa al caso tuo!',
        ],
        [
            'user_id' => 33,
            'title' => 'Tecnico del suono',
            'hourly_rate' => 150,00,
            'description' => 'Se ti serve un professionista per rendere il tuo live indimenticabile, rivolgiti ad un Tecnico del suono!',
        ],
        [
            'user_id' => 34,
            'title' => 'Band',
            'hourly_rate' => 10,00,
            'description' => 'Se nella tua band hai un posto libero, perché non chiedere aiuto ad un professionista? Potreste fare amicizia e vivere insieme esperienze incredibili!',
        ],
        [
            'user_id' => 35,
            'title' => 'Autore',
            'hourly_rate' => 50,00,
            'description' => "Non trovi l'ispirazione giusta per i tuoi testi ma la tua musica spacca? Rivolgiti ad uno dei nostri bardi, che provvederà ad aiutrti con le tue liriche!",
        ],
        [
            'user_id' => 36,
            'title' => 'Compositore',
            'hourly_rate' => 50,00,
            'description' => "Se vuoi trovare arranggiamenti per le tue composizioni per ottenere musiche sensazionali, contattami! Sono il Bardo che fa al caso tuo!",
        ],        [
            'user_id' => 37,
            'title' => 'Tournista',
            'hourly_rate' => 100,00,
            'description' => 'Stai per andare a fare un live e ti manca un componente? Ecco il tipo di performance che fa per te!',
        ],
        [
            'user_id' => 39,
            'title' => 'Insegnante',
            'hourly_rate' => 25,00,
            'description' => 'Se stai imparando uno strumento e vuoi intraprendere un percorso di apprendimento, questo è il tipo di performance che fa al caso tuo!',
        ],
        [
            'user_id' => 40,
            'title' => 'Tecnico del suono',
            'hourly_rate' => 150,00,
            'description' => 'Se ti serve un professionista per rendere il tuo live indimenticabile, rivolgiti ad un Tecnico del suono!',
        ],
        [
            'user_id' => 41,
            'title' => 'Band',
            'hourly_rate' => 10,00,
            'description' => 'Se nella tua band hai un posto libero, perché non chiedere aiuto ad un professionista? Potreste fare amicizia e vivere insieme esperienze incredibili!',
        ],
        [
            'user_id' => 42,
            'title' => 'Autore',
            'hourly_rate' => 50,00,
            'description' => "Non trovi l'ispirazione giusta per i tuoi testi ma la tua musica spacca? Rivolgiti ad uno dei nostri bardi, che provvederà ad aiutrti con le tue liriche!",
        ],
        [
            'user_id' => 43,
            'title' => 'Compositore',
            'hourly_rate' => 50,00,
            'description' => "Se vuoi trovare arranggiamenti per le tue composizioni per ottenere musiche sensazionali, contattami! Sono il Bardo che fa al caso tuo!",
        ],
        [
            'user_id' => 44,
            'title' => 'Tournista',
            'hourly_rate' => 100,00,
            'description' => 'Stai per andare a fare un live e ti manca un componente? Ecco il tipo di performance che fa per te!',
        ],
        [
            'user_id' => 45,
            'title' => 'Insegnante',
            'hourly_rate' => 25,00,
            'description' => 'Se stai imparando uno strumento e vuoi intraprendere un percorso di apprendimento, questo è il tipo di performance che fa al caso tuo!',
        ],
        [
            'user_id' => 46,
            'title' => 'Tecnico del suono',
            'hourly_rate' => 150,00,
            'description' => 'Se ti serve un professionista per rendere il tuo live indimenticabile, rivolgiti ad un Tecnico del suono!',
        ],
        [
            'user_id' => 47,
            'title' => 'Band',
            'hourly_rate' => 10,00,
            'description' => 'Se nella tua band hai un posto libero, perché non chiedere aiuto ad un professionista? Potreste fare amicizia e vivere insieme esperienze incredibili!',
        ],
        [
            'user_id' => 5,
            'title' => 'Autore',
            'hourly_rate' => 50,00,
            'description' => "Non trovi l'ispirazione giusta per i tuoi testi ma la tua musica spacca? Rivolgiti ad uno dei nostri bardi, che provvederà ad aiutrti con le tue liriche!",
        ],
        [
            'user_id' => 48,
            'title' => 'Compositore',
            'hourly_rate' => 50,00,
            'description' => "Se vuoi trovare arranggiamenti per le tue composizioni per ottenere musiche sensazionali, contattami! Sono il Bardo che fa al caso tuo!",
        ],
        [
            'user_id' => 49,
            'title' => 'Tournista',
            'hourly_rate' => 100,00,
            'description' => 'Stai per andare a fare un live e ti manca un componente? Ecco il tipo di performance che fa per te!',
        ],
        [
            'user_id' => 50,
            'title' => 'Insegnante',
            'hourly_rate' => 25,00,
            'description' => 'Se stai imparando uno strumento e vuoi intraprendere un percorso di apprendimento, questo è il tipo di performance che fa al caso tuo!',
        ],
    ]

 ?>