<?php 
    // ARRAY CON NOMI 'VERITIERI'
    return [
        [
            'name' => 'Vasco',
            'lastname' => 'Di Vincenzo',
            'address' => 'Via Cesare Battisti, 22',
            'email' => 'vascodivince@email.it',
        ],
        [
            'name' => 'Marco',
            'lastname' => 'Crimi',
            'address' => 'Via Cavour, 12',
            'email' => 'mcrimi@email.it',
        ],
        [
            'name' => 'Tiziana',
            'lastname' => 'Sensi',
            'address' => 'Piazza Albegna, 30',
            'email' => 'sensit@email.it',
        ],
        [
            'name' => 'Marta',
            'lastname' => 'De Lello',
            'address' => 'Via Brigate Partigiane, 61',
            'email' => 'delellomarta@email.it',
        ],
        [
            'name' => 'Paolo',
            'lastname' => 'Gravani',
            'address' => 'Via Carmelo Bene, 55',
            'email' => 'gravanipaolo@email.it',
        ],
        [
            'name' => 'Carlotta',
            'lastname' => 'Martini',
            'address' => 'Piazza Garibaldi, 9',
            'email' => 'carlottamar@email.it',
        ],
        [
            'name' => 'Nunzio',
            'lastname' => 'Parmesani',
            'address' => 'Via dei Barberi, 89',
            'email' => 'nunzioparme@email.it',
        ],
        [
            'name' => 'Michele',
            'lastname' => 'Scolini',
            'address' => 'Viale Einaudi, 34',
            'email' => 'scolinimichele@email.it',
        ],
        [
            'name' => 'Andrea',
            'lastname' => 'Passalacqua',
            'address' => 'Viale Giotto, 40',
            'email' => 'andrepassa@email.it',
        ],
        [
            'name' => 'Cinzia',
            'lastname' => 'Caroli',
            'address' => 'Viale Messina, 50',
            'email' => 'carolicinzia@email.it',
        ],
        [
            'name' => 'Sandro',
            'lastname' => 'Zacchini',
            'address' => 'Via Fiore, 59',
            'email' => 'zacchesandro@email.it',
        ],
        [
            'name' => 'Cesare',
            'lastname' => 'Murri',
            'address' => 'Via delle Fontane, 13',
            'email' => 'murricesare@email.it',
        ],
        [
            'name' => 'Milena',
            'lastname' => 'Canuti',
            'address' => 'Via Eugenio Montale, 67',
            'email' => 'milenacanuti@email.it',
        ],
        [
            'name' => 'Duccio',
            'lastname' => 'Barbieri',
            'address' => 'Via Cesare Battisti, 22',
            'email' => 'ducciobarbieri@email.it',
        ],
        [
            'name' => 'Manuela',
            'lastname' => 'Piccolonni',
            'address' => 'Viale Giuseppe Verdi, 77',
            'email' => 'manupiccolomini@email.it',
        ],
        [
            'name' => 'Barbara',
            'lastname' => 'Scaranti',
            'address' => 'Viale Padova, 18',
            'email' => 'scarantibarb@email.it',
        ],
        [
            'name' => 'Plinio',
            'lastname' => 'Ascani',
            'address' => 'Viale della Pala, 59',
            'email' => 'plinissimo@email.it',
        ],
        [
            'name' => 'Cianuro',
            'lastname' => 'Bastioni',
            'address' => 'Viale dei Cantori, 1',
            'email' => 'ciaocianuro@email.it',
        ],
        [
            'name' => 'Kaylash',
            'lastname' => 'Sere',
            'address' => 'Via Saffi, 22',
            'email' => 'kaysere@email.it',
        ],
        [
            'name' => 'Ivaldo',
            'lastname' => 'Saccaramanni',
            'address' => 'Via San Martino, 102',
            'email' => 'ivaldoaldo@email.it',
        ],
        [
            'name' => 'Vlad',
            'lastname' => 'Il vampiro',
            'address' => 'Via Fragola, 66',
            'email' => 'vlady@email.it',
        ],
        [
            'name' => 'Jerry',
            'lastname' => 'Ciampi',
            'address' => 'Via Manzoni, 77',
            'email' => 'jciampi@email.it',
        ],
        [
            'name' => 'Stefano',
            'lastname' => 'Benvenuti',
            'address' => 'Via Ximenes, 17',
            'email' => 'benvenutistefano@email.it',
        ],
        [
            'name' => 'Giorgia',
            'lastname' => 'Canestri',
            'address' => 'Piazza Lulli, 3',
            'email' => 'giorgiacane@email.it',
        ],
        [
            'name' => 'Paolo',
            'lastname' => 'Gennari',
            'address' => 'Via Latina, 3',
            'email' => 'gennypaolo@email.it',
        ],
        [
            'name' => 'Stefano',
            'lastname' => 'Bollani',
            'address' => 'Piazza San Francesco, 88',
            'email' => 'stefanoboll@email.it',
        ],
        [
            'name' => 'Fabri',
            'lastname' => 'Fibra',
            'address' => 'Viale Vicenza, 66',
            'email' => 'fibrafabri@email.it',
        ],
        [
            'name' => 'Tullio',
            'lastname' => 'De Piscopo',
            'address' => 'Viale Salerno, 81',
            'email' => 'tulliodepiscopo@email.it',
        ],
        [
            'name' => 'Salmo',
            'lastname' => 'Lebon',
            'address' => 'Via delle Rose, 11',
            'email' => 'salmo@email.it',
        ],
        [
            'name' => 'Kaos',
            'lastname' => 'One',
            'address' => 'Viale Padova, 76',
            'email' => 'kaosone@email.it',
        ],
        [
            'name' => 'Francesco',
            'lastname' => 'Guccini',
            'address' => 'Via Emilia, 68',
            'email' => 'fraguccini@email.it',
        ],
        [
            'name' => 'Ice',
            'lastname' => 'One',
            'address' => 'Via Roma, 14',
            'email' => 'iceone@email.it',
        ],
        [
            'name' => 'Rudy',
            'lastname' => 'Zerbi',
            'address' => 'Via Latina, 44',
            'email' => 'rudyzb@email.it',
        ],
        [
            'name' => 'Mara',
            'lastname' => 'Maionchi',
            'address' => 'Via dei Mille, 99',
            'email' => 'mmaionchi@email.it',
        ],
        [
            'name' => 'Angelo',
            'lastname' => 'Branduardi',
            'address' => 'Via Castro, 53',
            'email' => 'angelobranduardi@email.it',
        ],
        [
            'name' => 'Clementino',
            'lastname' => 'Iena',
            'address' => 'Viale Ungaretti, 29',
            'email' => 'clementeiena@email.it',
        ],
        [
            'name' => 'Franz',
            'lastname' => 'Di Cioccio',
            'address' => 'Viale Pescara, 37',
            'email' => 'fdicioccio@email.it',
        ],
        [
            'name' => 'Danno',
            'lastname' => 'LaMotta',
            'address' => 'Via Roma, 23',
            'email' => 'jakelamotta@email.it',
        ],
        [
            'name' => 'Vinnie',
            'lastname' => 'Colaiuta',
            'address' => 'Via Washington, 45',
            'email' => 'vinniecola@email.it',
        ],
        [
            'name' => 'Les',
            'lastname' => 'Claypool',
            'address' => 'Viale Sardegna, 68',
            'email' => 'primuskingdom@email.it',
        ],
        [
            'name' => 'Primo',
            'lastname' => 'Brown',
            'address' => 'Via Canova, 100',
            'email' => 'primobrown@email.it',
        ],
    ]

 ?>