<?php 
    // ARRAY CON NOMI 'VERITIERI'
    return [
        [
            'name' => 'Vasco',
            'lastname' => 'Di Vincenzo',
            'address' => 'Via Cesare Battisti, 22',
            'email' => 'vascodivince@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Marco',
            'lastname' => 'Crimi',
            'address' => 'Via Cavour, 12',
            'email' => 'mcrimi@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Tiziana',
            'lastname' => 'Sensi',
            'address' => 'Piazza Albegna, 30',
            'email' => 'sensit@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Marta',
            'lastname' => 'De Lello',
            'address' => 'Via Brigate Partigiane, 61',
            'email' => 'delellomarta@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Paolo',
            'lastname' => 'Gravani',
            'address' => 'Via Carmelo Bene, 55',
            'email' => 'gravanipaolo@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Carlotta',
            'lastname' => 'Martini',
            'address' => 'Piazza Garibaldi, 9',
            'email' => 'carlottamar@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Nunzio',
            'lastname' => 'Parmesani',
            'address' => 'Via dei Barberi, 89',
            'email' => 'nunzioparme@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Michele',
            'lastname' => 'Scolini',
            'address' => 'Viale Einaudi, 34',
            'email' => 'scolinimichele@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Andrea',
            'lastname' => 'Passalacqua',
            'address' => 'Viale Giotto, 40',
            'email' => 'andrepassa@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Cinzia',
            'lastname' => 'Caroli',
            'address' => 'Viale Messina, 50',
            'email' => 'carolicinzia@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Sandro',
            'lastname' => 'Zacchini',
            'address' => 'Via Fiore, 59',
            'email' => 'zacchesandro@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Cesare',
            'lastname' => 'Murri',
            'address' => 'Via delle Fontane, 13',
            'email' => 'murricesare@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Milena',
            'lastname' => 'Canuti',
            'address' => 'Via Eugenio Montale, 67',
            'email' => 'milenacanuti@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Duccio',
            'lastname' => 'Barbieri',
            'address' => 'Via Cesare Battisti, 22',
            'email' => 'ducciobarbieri@email.it',
            'password' => 'cavecanem',
        ],
        [
            'name' => 'Manuela',
            'lastname' => 'Piccolonni',
            'address' => 'Viale Giuseppe Verdi, 77',
            'email' => 'manupiccolomini@email.it',
            'password' => 'cavecanem',
        ],
    ]

 ?>